name: elderly_care
description: A digital companion app for senior citizens
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.0.0
  provider: ^6.0.5
  intl: ^0.18.0
  flutter_secure_storage: ^8.0.0
  google_fonts: ^5.1.0
  avatar_glow: ^2.0.2
  speech_to_text: ^7.0.0
  timeago: ^3.5.0
  cached_network_image: ^3.3.0
  http: ^1.1.0
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  